# -*- Mode: makefile-gmake -*-

.PHONY: all debug release clean test-clean

#
# Real makefile defines EXE (and possibly SRC and GEN_SRC) and includes
# this one.
#

ifndef EXE
${error EXE not defined}
endif

#
# Required packages
#

PKGS = gio-unix-2.0 gio-2.0 libglibutil
LIB_PKGS = $(PKGS)

#
# Default target
#

all: debug release

#
# Sources
#

SRC ?= $(EXE).c
ALL_SRC = $(GEN_SRC) $(SRC)

#
# Directories
#

SRC_DIR = .
BUILD_DIR = build
TOP_DIR = ../..
SPEC_DIR = $(TOP_DIR)/plugins/dbus_service
DEBUG_BUILD_DIR = $(BUILD_DIR)/debug
RELEASE_BUILD_DIR = $(BUILD_DIR)/release

#
# Tools and flags
#

CC = $(CROSS_COMPILE)gcc
LD = $(CC)
DEBUG_FLAGS =
RELEASE_FLAGS =
DEBUG_DEFS = -DDEBUG
RELEASE_DEFS =
WARNINGS = -Wall -Wstrict-aliasing -Wunused-result
INCLUDES = -I. -I$(TOP_DIR)/core/include
FULL_CFLAGS = -fPIC $(CFLAGS) $(DEFINES) $(WARNINGS) $(INCLUDES) \
  -MMD -MP $(shell pkg-config --cflags $(PKGS)) -g
FULL_LDFLAGS = $(LDFLAGS)

DEBUG_CFLAGS = $(DEBUG_FLAGS) -I$(DEBUG_BUILD_DIR) -DDEBUG $(FULL_CFLAGS)
RELEASE_CFLAGS = $(RELEASE_FLAGS) -I$(RELEASE_BUILD_DIR) -O2 $(FULL_CFLAGS)
DEBUG_LDFLAGS = $(DEBUG_FLAGS) $(FULL_LDFLAGS)
RELEASE_LDFLAGS = $(RELEASE_FLAGS) $(FULL_LDFLAGS)

LIBS = $(shell pkg-config --libs $(LIB_PKGS)) -ldl
DEBUG_LIBS = $(LIBS)
RELEASE_LIBS = $(LIBS)

#
# Files
#

DEBUG_GEN_SRC = $(GEN_SRC:%.c=$(DEBUG_BUILD_DIR)/%.c)
RELEASE_GEN_SRC = $(GEN_SRC:%.c=$(RELEASE_BUILD_DIR)/%.c)
DEBUG_OBJS = $(ALL_SRC:%.c=$(DEBUG_BUILD_DIR)/%.o)
RELEASE_OBJS = $(ALL_SRC:%.c=$(RELEASE_BUILD_DIR)/%.o)

#
# Dependencies
#

DEPS = \
  $(DEBUG_OBJS:%.o=%.d) \
  $(RELEASE_OBJS:%.o=%.d)
ifneq ($(MAKECMDGOALS),clean)
ifneq ($(strip $(DEPS)),)
-include $(DEPS)
endif
endif

$(DEBUG_GEN_SRC) $(DEBUG_OBJS): | $(DEBUG_BUILD_DIR)
$(RELEASE_GEN_SRC) $(RELEASE_OBJS): | $(RELEASE_BUILD_DIR)
$(SRC:%.c=$(DEBUG_BUILD_DIR)/%.o): | $(DEBUG_GEN_SRC)
$(SRC:%.c=$(RELEASE_BUILD_DIR)/%.o): | $(RELEASE_GEN_SRC)

#
# Rules
#

DEBUG_EXE = $(DEBUG_BUILD_DIR)/$(EXE)
RELEASE_EXE = $(RELEASE_BUILD_DIR)/$(EXE)

debug: $(DEBUG_EXE)

release: $(RELEASE_EXE)

test-clean: clean

clean:
	rm -fr $(BUILD_DIR) $(SRC_DIR)/*~

$(DEBUG_BUILD_DIR)/%.c: $(SPEC_DIR)/%.xml
	gdbus-codegen --generate-c-code $(@:%.c=%) $<

$(RELEASE_BUILD_DIR)/%.c: $(SPEC_DIR)/%.xml
	gdbus-codegen --generate-c-code $(@:%.c=%) $<

$(DEBUG_BUILD_DIR) $(RELEASE_BUILD_DIR):
	mkdir -p $@

$(DEBUG_BUILD_DIR)/%.o: $(DEBUG_BUILD_DIR)/%.c
	$(CC) -c $(DEBUG_CFLAGS) -MT"$@" -MF"$(@:%.o=%.d)" $< -o $@

$(RELEASE_BUILD_DIR)/%.o: $(RELEASE_BUILD_DIR)/%.c
	$(CC) -c $(RELEASE_CFLAGS) -MT"$@" -MF"$(@:%.o=%.d)" $< -o $@

$(DEBUG_BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	$(CC) -c $(WARN) $(DEBUG_CFLAGS) -MT"$@" -MF"$(@:%.o=%.d)" $< -o $@

$(RELEASE_BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	$(CC) -c $(WARN) $(RELEASE_CFLAGS) -MT"$@" -MF"$(@:%.o=%.d)" $< -o $@

$(DEBUG_EXE): $(DEBUG_OBJS)
	$(LD) $(DEBUG_LDFLAGS) $(DEBUG_OBJS) $(DEBUG_LIBS) -o $@

$(RELEASE_EXE): $(RELEASE_OBJS)
	$(LD) $(RELEASE_LDFLAGS) $(RELEASE_OBJS) $(RELEASE_LIBS) -o $@
