# -*- Mode: makefile-gmake -*-

EXE = test_plugins_dbus_service_plugin

COMMON_SRC = test_main.c test_adapter.c test_target.c \
    test_dbus.c test_dbus_name.c

EXTRA_EXE_LDFLAGS = -u nfc_core_version

include ../common/Makefile.plugins
