#!/bin/bash
#
# This script requires lcov, dirname
#

TESTS="\
core_adapter \
core_config \
core_crc \
core_host \
core_initiator \
core_llc \
core_llc_param \
core_manager \
core_ndef_rec \
core_ndef_rec_sp \
core_ndef_rec_t \
core_ndef_rec_u \
core_peer \
core_peer_service \
core_peer_services \
core_peer_socket \
core_plugin \
core_plugins \
core_snep \
core_tag \
core_tag_t2 \
core_tag_t4 \
core_target \
core_util \
plugins_dbus_handlers \
plugins_dbus_handlers_config \
plugins_dbus_handlers_type_generic \
plugins_dbus_handlers_type_mediatype \
plugins_dbus_handlers_type_sp \
plugins_dbus_handlers_type_text \
plugins_dbus_handlers_type_uri \
plugins_dbus_service_adapter \
plugins_dbus_service_host \
plugins_dbus_service_isodep \
plugins_dbus_service_local_app \
plugins_dbus_service_local_host \
plugins_dbus_service_ndef \
plugins_dbus_service_peer \
plugins_dbus_service_plugin \
plugins_dbus_service_tag \
plugins_dbus_service_tag_t2 \
plugins_dbus_service_util \
plugins_settings"

function err() {
    echo "*** ERROR!" $1
    exit 1
}

# Check the required tools
which lcov >> /dev/null || err "Please install lcov"
which dirname >> /dev/null || err "Please install dirname"

# LCOV 1.10 has branch coverage disabled per default
# Previous versions didn't have the --rc option
if  [ ! -z "$(lcov --help | grep ' --rc ')" ] ; then
    LCOV_OPT="--rc branch_coverage=1"
    GENHTML_OPT="--branch-coverage"
fi

# If specific tests are provided on the command line, only run those
if [ $# -gt 0 ] ; then
    TESTS="$@"
    # Since we are not compiling all tests, some directories may remain empty.
    # Options have to be repeated to suppress multiple errors/warnings
    LCOV_OPT+=" --rc ignore_errors=unused,unused,empty,empty"
fi

pushd `dirname $0` > /dev/null
COV_DIR="$PWD"
pushd .. > /dev/null
TEST_DIR="$PWD"
pushd .. > /dev/null
TOP_DIR="$PWD"
CORE_DIR="$TOP_DIR/core"
PLUGINS_DIR="$TOP_DIR/plugins"
popd > /dev/null
popd > /dev/null
popd > /dev/null

make -C "$TOP_DIR" clean
for t in $TESTS ; do
    pushd "$TEST_DIR/$t"
    make -j -C "$TEST_DIR/$t" coverage || exit 1
    # Run the same test with and without debug trace to maximize coverage
    build/coverage/test_$t || exit 1
    build/coverage/test_$t -v || exit 1
    popd
done

CORE_COV="$COV_DIR/core.gcov"
PLUGINS_COV="$COV_DIR/plugins.gcov"
ALL_COV="$COV_DIR/all.gcov"
FILTERED_COV="$COV_DIR/filtered.gcov"
rm -f "$CORE_COV" "$PLUGINS_COV" "$ALL_COV" "$FILTERED_COV"

# At least some core coverage is expected to always be there
lcov $LCOV_OPT -c -d "$CORE_DIR/build/coverage" -b "$CORE_DIR" -o "$CORE_COV" || exit 1
lcov $LCOV_OPT -a "$CORE_COV" -o "$ALL_COV"

# Plugin coverage data may be missing if we are not running all tests
PLUGINS_COVERAGE_DIR="$PLUGINS_DIR/build/coverage"
if [ -d "$PLUGINS_COVERAGE_DIR" ] ; then
    lcov $LCOV_OPT -c -d "$PLUGINS_COVERAGE_DIR" -b "$PLUGINS_DIR" -o "$PLUGINS_COV" || exit 1
    lcov $LCOV_OPT -a "$PLUGINS_COV" -o "$ALL_COV"
fi

lcov $LCOV_OPT -e "$ALL_COV" "$CORE_DIR/src/*" "$PLUGINS_DIR/dbus_handlers/*" "$PLUGINS_DIR/dbus_service/*" "$PLUGINS_DIR/settings/*" -o "$FILTERED_COV" || exit 1
genhtml $GENHTML_OPT "$FILTERED_COV" -t "nfcd" --output-directory "$COV_DIR/report" || exit 1
