# -*- Mode: makefile-gmake -*-

EXE = test_plugins_settings

COMMON_SRC = test_dbus.c test_main.c

EXTRA_EXE_LDFLAGS = -u nfc_core_version -u nfc_configurable_get_type

include ../common/Makefile.plugins
